# Generated by Django 3.0.1 on 2019-12-19 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=50)),
                ('guests', models.CharField(max_length=10)),
                ('booked_name', models.CharField(max_length=100)),
                ('booked_email', models.CharField(max_length=200)),
                ('booked_phone', models.CharField(max_length=100)),
                ('booked_date', models.DateField(default=datetime.date.today)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='app.Restaurant')),
            ],
        ),
    ]
